ALTER TABLE employee ADD COLUMN "status" VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE department ADD COLUMN "status" VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE assignment ADD COLUMN "status" VARCHAR(20) DEFAULT 'ACTIVE';
